Implement Comprehensive Metrics Tracking System
rootCircle/symmetrical-octo-spork pull request #63
Opened 2024-12-14 11:15 UTC by Gyan172004

## Overview

This pull request introduces a comprehensive metrics tracking system for the docFiller project, which includes the following changes:

- **Metrics Management**: Centralized management of metrics using a singleton pattern.
- **Analytics**: Calculation of key metrics such as API call performance and usage tracking.
- **UI Integration**: Added UI components to display and visualize metrics data in the options page.

## Changes Made

### Metrics System Implementation
- **/src/utils/metricsCalculator.ts**: Core logic for calculating and processing metrics data.
- **/src/utils/metricsManager.ts**: Singleton for managing metrics data centrally across the application.
- **/src/background/index.ts**: Integrated metrics tracking for API calls and background processes.
- **/src/options/metrics.ts**: UI components for displaying and interacting with metrics data in the options page.

### Storage Integration
- **/src/utils/storage/metricsStorage.ts**: Handles persistent storage of metrics data.
- **/src/utils/storage/getMetrics.ts**: Functions for retrieving metrics data from storage.
- **/src/utils/storage/setMetrics.ts**: Functions for storing updated metrics data.

### LLM Engine Integration
- **/src/docFillerCore/engines/gptEngine.ts**: Added performance tracking hooks to measure LLM engine performance.
- **/src/utils/llmEngineTypes.ts**: New type definitions related to metrics and LLM engine.

### UI Components
- **/src/options/options.ts**: Added a section to the options page for displaying metrics data.
- **/src/components/MetricsCard.tsx**: A reusable component for visualizing metrics on the UI.
- **/src/styles/metrics.css**: Styling and layout for metrics UI components.

## Technical Notes

- **Rolling History**: All metrics data maintains a 14-day rolling history for performance and usage tracking.
- **Type Safety**: TypeScript interfaces are used to ensure type safety across the metrics system.
- **Real-time Updates**: Implemented real-time updates using the Chrome storage API and event listeners.

## Testing

- Ensure metrics data is being properly calculated and stored.
- Verify that UI components are displaying the correct metrics.
- Confirm that the storage integration works as expected, including retrieval and update of metrics data.

## Screenshot
![Screenshot 2024-12-14 164428](https://github.com/user-attachments/assets/fb4fd7e6-9fab-4cf1-aa87-d1cbc9ce3ef8)

---

Please review the changes and let me know if you have any questions or feedback.

2024-12-14 16:10 UTC, rootCircle commented
This looks awesome! :star_struck:

2024-12-14 18:28 UTC, rootCircle requested changes
I trust you :sweat_smile:

2024-12-14 18:28 UTC, rootCircle commented on src/utils/storage/metricsManager.ts
> +  private static readonly MAX_HISTORY_DAYS = 14;
how are we using this?

2024-12-14 18:28 UTC, rootCircle commented on package-lock.json
delete file, we use bun, also check if it's in gitignore or not. If not add package-lock.json to gitignore

2024-12-14 18:28 UTC, rootCircle commented on src/docFillerCore/index.ts
> +  if (
can we make this if condition, a bit more readable?

use boolean variables instead?

2024-12-14 18:28 UTC, rootCircle commented on src/docFillerCore/index.ts
> +  if (
I believe this must be about disallowing filling if config is broken?

2024-12-14 18:28 UTC, rootCircle commented on src/docFillerCore/index.ts
> +  if (
add a helpful message in console as well

2024-12-14 18:55 UTC, Gyan172004 commented on src/utils/storage/metricsManager.ts
> +  private static readonly MAX_HISTORY_DAYS = 14;
Its make to manage state for metrics and managing its properties like updating them

2024-12-14 19:36 UTC, Gyan172004 commented on src/docFillerCore/index.ts
> +  if (
Figured out we already have correct invalid engine logic implemented in  `validateLLMConfiguration` handling both states of consensus engine .
Cleaned up the if condition, made it more readable, and added a helpful console message.

2024-12-14 19:42 UTC, rootCircle approved these changes

2024-12-14 19:47 UTC, Gyan172004 commented on src/utils/storage/metricsManager.ts
> +  private static readonly MAX_HISTORY_DAYS = 14;
MAX_HISTORY_DAYS is to limit storage of data , everytime form is filled , we sort history data structure in recently first manner and then slice 14 days (2 week) history.

2024-12-14 20:10 UTC, Gyan172004 commented on src/utils/storage/metricsManager.ts
> +  private static readonly MAX_HISTORY_DAYS = 14;
Better way can be we can reset it after total_forms>1000?

2024-12-15 12:16 UTC, rootCircle commented on src/utils/storage/metricsManager.ts
> +  private static readonly MAX_HISTORY_DAYS = 14;
We can create it to store metadata > 14 days via aggregation! Details of which are beyond scope of this PR!

2024-12-15 12:17 UTC, merged