dynamic manifest
rootCircle/symmetrical-octo-spork pull request #72
Opened 2024-12-19 23:09 UTC by Gyan172004

## Dynamic Manifest Generation for Cross-Browser Support
Fixes #70

Implemented dynamic manifest.json generation to support both Firefox and Chrome browsers individually. This change ensures proper browser-specific configurations are generated during build time.

### Key Changes

- Added manifest generation logic to handle browser-specific requirements

- -Firefox requires `browser_specific_settings` and `background.scripts`

- Chrome/Edge use `background.service_worker`

- Modified watcher.ts to prevent manifest overwriting during file operations

- Added filtering in file copy operations to preserve generated manifests

2024-12-20 11:16 UTC, rootCircle requested changes

2024-12-20 11:16 UTC, rootCircle commented on package.json
> +    "build": "bun run build:firefox",
Remove `build` and `package` scripts as they can be confusing in general for end user!

2024-12-20 11:16 UTC, rootCircle commented on tools/builder.ts
> -  await copyContents('./public', './build');
Instead of removing this, we can delete manifest.json, as it is now dynamically generated and hence not needed in public folder!

2024-12-20 11:16 UTC, rootCircle commented on tools/builder.ts
> -  await copyContents('./public', './build');
Also check for extra dependencies that might be related to this as well and remove this if not needed!

2024-12-20 11:16 UTC, rootCircle commented on tools/manifest.ts
> +  const isFirefox = process.env.BROWSER === 'firefox';
is not firefox doesn't means it's chromium always, it might have some invalid value as well!

Add an extra isChromiumBased which checks if browser is chromium based like chrome, brave, opera, edge, chromium and act accordingly!

If it is neither of both throw an error saying unsupported browser!

2024-12-20 11:16 UTC, rootCircle commented on tools/manifest.ts
> +    background: isFirefox
Ternary (if else) is not suitable here, instead use isFirefoxBased -> this
isChromiumBased then this

2024-12-20 11:16 UTC, rootCircle commented on tools/manifest.ts
> +  const isFirefox = process.env.BROWSER === 'firefox';
Also change isFirefox tisFirefoxBased and ensure isChromiumBased and isFirefoxBased are not true at same time!

2024-12-20 11:16 UTC, rootCircle commented on tools/manifest.ts
> +    ...(isFirefox && {
Put this inside gecko(not complete browser_specific_settings) as browser_specific_settings are not native to firefox, but safari too supports this! (Not chromium based browsers)

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#firefox_gecko_properties

2024-12-20 11:16 UTC, rootCircle commented on tools/manifest.ts
> +      `✓ manifest.json generated for ${process.env.BROWSER || 'chromium'}`,
As discussed earlier, we can't have a default browser environment as it will lead to confusion!

If process.env.BROWSER is empty or invalid, error out prematurely!

2024-12-20 11:16 UTC, rootCircle commented on tools/bundler.ts
> +  await writeManifest();
Can we move writeManifest under runBuild function? It keeps the logic more coupled!

2024-12-20 11:16 UTC, rootCircle commented on tools/watcher.ts
> +      if (!(error.code === 'ENOENT' || error.code === 'EPERM')) {
Why are we silenting these errors?

2024-12-20 17:10 UTC, rootCircle requested changes

2024-12-20 17:10 UTC, rootCircle commented on Makefile
> +	bun run build:firefox && bun run build:chromium
Change build to build-firefox and build-chromium, this will not make sense, if we actually want the build folder as chromium will overwrite the firefox one's build

2024-12-20 17:10 UTC, rootCircle commented on tools/watcher.ts
> +      await fs.copy('./public', './build', {
We can use `copyContents` method code here! No need for fs.copy

2024-12-20 17:10 UTC, rootCircle commented on tools/watcher.ts
> +  await writeManifest();
This won't trigger when manifest is updated! Earlier it did!

Possible resolution would be to move writeManifest() to runBuild() method itself

2024-12-20 17:10 UTC, rootCircle commented on tools/manifest.ts
> +  const browser = process.env.BROWSER?.toLowerCase();
There is no need to change the case of input, use the input as is

There should be preferably only one way to do things!

Also change variable to more semantically correct name like targetBrowser etc

2024-12-20 17:10 UTC, rootCircle commented on tools/manifest.ts
> +  if (!browser) {
Move this condition above these two!

Also there is no need to check for nullability(??) in both variables! (After you shift them up)

2024-12-20 17:10 UTC, rootCircle commented on tools/manifest.ts
> +        gecko: {
As discussed earlier, you need to put isFirefoxBased under gecko

2024-12-20 17:10 UTC, rootCircle commented on tools/manifest.ts
> +}
Better to segregate runner with caller,

You can make a new file called manifestWriter.ts or similar and use that there!

2024-12-25 20:14 UTC, rootCircle requested changes

2024-12-25 20:14 UTC, rootCircle commented on tools/watcher.ts
> +const buildWatch = async () => {
remove async marker, not needed!

2024-12-25 20:14 UTC, rootCircle commented on tools/watcher.ts
> +  await runBuild(true).catch(console.error);
we don't need to await this callback!

2024-12-25 20:14 UTC, rootCircle commented on tools/watcher.ts
> +      copyContents('./public/src', './build/src');
Why these instead of simple `copyContents('./public', './build').catch(console.error)`?

2024-12-25 20:14 UTC, rootCircle commented on tools/watcher.ts
> +      await runBuild(true);
we don't need this as the callback of runBuild will automatically handle watching

2024-12-25 20:14 UTC, rootCircle commented on tools/manifest.ts
> +}
call this in manifestWriter.ts file only

2024-12-25 20:14 UTC, rootCircle commented on tools/builder.ts
> +  copyContents('./public/src', './build/src');
why this instead of `copyContents('./public', './build').catch(console.error);`?

2024-12-25 20:14 UTC, rootCircle commented on tools/watcher.ts
>    });
add a watch on manifest.ts, so if our manifest.ts changes the code adopts accordingly!

2024-12-25 20:14 UTC, rootCircle commented on tools/manifest.ts
better to move this under `src`, so we can better track changes. (not for manifestWriter)

2024-12-25 21:11 UTC, rootCircle requested changes

2024-12-25 21:11 UTC, rootCircle commented on tools/watcher.ts
> +    }
there is no need of try catch here as we're already handling that in callback

2024-12-25 21:11 UTC, rootCircle commented on tools/watcher.ts
> +  const watcher = chokidar.watch(['public/', 'manifest.ts'], {
change manifest.ts to src/manifest.ts 

and move tools/manifest.ts to src/manifest.ts

2024-12-25 21:11 UTC, rootCircle commented on tools/manifest.ts
move it to src/manifest.ts

2024-12-25 21:28 UTC, rootCircle requested changes

2024-12-25 21:28 UTC, rootCircle commented on tools/builder.ts
> +  copyContents('./public', './build').catch(console.error);
can we convert this to await back again, callbacks can cause race conditions

2024-12-25 21:28 UTC, rootCircle commented on tools/builder.ts
> +      format: 'esm',
remove these, node is not the platform, it's browser, but it's by default so not required here

2024-12-25 21:28 UTC, rootCircle commented on tools/builder.ts
> +      format: 'esm',
remove these as well

2024-12-25 21:38 UTC, Gyan172004 commented on tools/builder.ts
> +      format: 'esm',
I was facing errors after moving it to src/ ,  about not being able to resolve Node.js built-in modules (path, url, fs, etc.)
since modules are meant for Node.js environment

2024-12-25 21:50 UTC, rootCircle requested changes

2024-12-25 21:50 UTC, rootCircle commented on tools/builder.ts
> +  await copyContents('./public', './build').catch(console.error);
there is no need of catch here!

2024-12-25 21:50 UTC, rootCircle commented on tools/builder.ts
> +      format: 'esm',
if that's the case then we can move manifest.ts to `public/manifest.ts`. Update reference in watcher.ts as well! But remove node platform as it can cause issues

2024-12-25 22:05 UTC, rootCircle approved these changes
LGTM :+1:

2024-12-25 22:06 UTC, merged